# Descomposición LU

In [1]:
%load_ext autoreload

In [2]:
%autoreload 2
from src import descomposicion_LU, eliminacion_gaussiana, matriz_aumentada
A = [[1, 2,-1, -1], [2, 3, -2,  -3], [1, 1, 1, 0], [1, 4, -1, 3]]
b = [4,1,-3,4]

Ab = matriz_aumentada(A, b)
eliminacion_gaussiana(Ab)

[07-18 11:33:31][INFO] 2024-07-18 11:33:31.824685
[07-18 11:33:31][INFO] 
[[ 1.  2. -1. -1.  4.]
 [ 0. -1.  0. -1. -7.]
 [ 0. -1.  2.  1. -7.]
 [ 0.  2.  0.  4.  0.]]
[07-18 11:33:31][INFO] 
[[  1.   2.  -1.  -1.   4.]
 [  0.  -1.   0.  -1.  -7.]
 [  0.   0.   2.   2.   0.]
 [  0.   0.   0.   2. -14.]]
[07-18 11:33:31][INFO] 
[[  1.   2.  -1.  -1.   4.]
 [  0.  -1.   0.  -1.  -7.]
 [  0.   0.   2.   2.   0.]
 [  0.   0.   0.   2. -14.]]


array([-24.,  14.,   7.,  -7.])

In [3]:
L, U = descomposicion_LU(A)

[07-18 11:33:31][INFO] 
[[ 1.  2. -1. -1.]
 [ 0. -1.  0. -1.]
 [ 0. -1.  2.  1.]
 [ 0.  2.  0.  4.]]
[07-18 11:33:31][INFO] 
[[ 1.  2. -1. -1.]
 [ 0. -1.  0. -1.]
 [ 0.  0.  2.  2.]
 [ 0.  0.  0.  2.]]
[07-18 11:33:31][INFO] 
[[ 1.  2. -1. -1.]
 [ 0. -1.  0. -1.]
 [ 0.  0.  2.  2.]
 [ 0.  0.  0.  2.]]
[07-18 11:33:31][INFO] 
[[ 1.  2. -1. -1.]
 [ 0. -1.  0. -1.]
 [ 0.  0.  2.  2.]
 [ 0.  0.  0.  2.]]


In [4]:
%autoreload 2
from src import descomposicion_LU

L, U = descomposicion_LU(A)
print(L)
print(U)

[07-18 11:33:31][INFO] 
[[ 1.  2. -1. -1.]
 [ 0. -1.  0. -1.]
 [ 0. -1.  2.  1.]
 [ 0.  2.  0.  4.]]
[07-18 11:33:31][INFO] 
[[ 1.  2. -1. -1.]
 [ 0. -1.  0. -1.]
 [ 0.  0.  2.  2.]
 [ 0.  0.  0.  2.]]
[07-18 11:33:31][INFO] 
[[ 1.  2. -1. -1.]
 [ 0. -1.  0. -1.]
 [ 0.  0.  2.  2.]
 [ 0.  0.  0.  2.]]
[07-18 11:33:31][INFO] 
[[ 1.  2. -1. -1.]
 [ 0. -1.  0. -1.]
 [ 0.  0.  2.  2.]
 [ 0.  0.  0.  2.]]
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 1.  1.  1.  0.]
 [ 1. -2.  0.  1.]]
[[ 1.  2. -1. -1.]
 [ 0. -1.  0. -1.]
 [ 0.  0.  2.  2.]
 [ 0.  0.  0.  2.]]


In [5]:
import numpy as np

np.matmul(L, U)

array([[ 1.,  2., -1., -1.],
       [ 2.,  3., -2., -3.],
       [ 1.,  1.,  1.,  0.],
       [ 1.,  4., -1.,  3.]])

In [6]:
%autoreload 2
from src import eliminacion_gaussiana, descomposicion_LU, resolver_LU

resolver_LU(L, U, b)

[07-18 11:33:32][INFO] Sustitución hacia adelante
[07-18 11:33:32][INFO] y = 
[[  4.]
 [ -7.]
 [  0.]
 [-14.]]
[07-18 11:33:32][INFO] Sustitución hacia atrás
[07-18 11:33:32][INFO] i = 2
[07-18 11:33:32][INFO] suma = [-14.]
[07-18 11:33:32][INFO] U[i, i] = 2.0
[07-18 11:33:32][INFO] y[i] = [0.]
[07-18 11:33:32][INFO] i = 1
[07-18 11:33:32][INFO] suma = [7.]
[07-18 11:33:32][INFO] U[i, i] = -1.0
[07-18 11:33:32][INFO] y[i] = [-7.]
[07-18 11:33:32][INFO] i = 0
[07-18 11:33:32][INFO] suma = [28.]
[07-18 11:33:32][INFO] U[i, i] = 1.0
[07-18 11:33:32][INFO] y[i] = [4.]


array([[-24.],
       [ 14.],
       [  7.],
       [ -7.]])

In [7]:
np.matmul(L, [4, -7, 0, -14])

array([ 4.,  1., -3.,  4.])

In [8]:
eliminacion_gaussiana(
    [
        [1.0, 2.0, -1.0, -1.0, 4.0],
        [2.0, 3.0, -2.0, -3.0, 1.0],
        [1.0, 1.0, 1.0, 0.0, -3.0],
        [1.0, 4.0, -1.0, 3.0, 4.0],
    ]
)

[07-18 11:33:32][INFO] 
[[ 1.  2. -1. -1.  4.]
 [ 0. -1.  0. -1. -7.]
 [ 0. -1.  2.  1. -7.]
 [ 0.  2.  0.  4.  0.]]
[07-18 11:33:32][INFO] 
[[  1.   2.  -1.  -1.   4.]
 [  0.  -1.   0.  -1.  -7.]
 [  0.   0.   2.   2.   0.]
 [  0.   0.   0.   2. -14.]]
[07-18 11:33:32][INFO] 
[[  1.   2.  -1.  -1.   4.]
 [  0.  -1.   0.  -1.  -7.]
 [  0.   0.   2.   2.   0.]
 [  0.   0.   0.   2. -14.]]


array([-24.,  14.,   7.,  -7.])

# Ejemplo 2

In [9]:
%autoreload 2
from src import separar_m_aumentada

Ab = [[1, 1, 0, 3, 4], [2, 1, -1, 1, 1], [3, -1, -1, 2, -3], [-1, 2, 3, -1, 4]]
sol = eliminacion_gaussiana(Ab)
print(sol)


[07-18 11:33:32][INFO] 
[[  1   1   0   3   4]
 [  0  -1  -1  -5  -7]
 [  0  -4  -1  -7 -15]
 [  0   3   3   2   8]]
[07-18 11:33:32][INFO] 
[[  1   1   0   3   4]
 [  0  -1  -1  -5  -7]
 [  0   0   3  13  13]
 [  0   0   0 -13 -13]]
[07-18 11:33:32][INFO] 
[[  1   1   0   3   4]
 [  0  -1  -1  -5  -7]
 [  0   0   3  13  13]
 [  0   0   0 -13 -13]]


[-1.  2.  0.  1.]


In [10]:
A, b = separar_m_aumentada(Ab)
L, U = descomposicion_LU(A)
print(L)
print(U)

[07-18 11:33:32][INFO] 
[[ 1.  1.  0.  3.]
 [ 0. -1. -1. -5.]
 [ 0. -4. -1. -7.]
 [ 0.  3.  3.  2.]]
[07-18 11:33:32][INFO] 
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]
[07-18 11:33:32][INFO] 
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]
[07-18 11:33:32][INFO] 
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]


In [11]:
%autoreload 2
from src import resolver_LU
s2 = resolver_LU(L, U, b)
s2

[07-18 11:33:32][INFO] Sustitución hacia adelante
[07-18 11:33:32][INFO] y = 
[[  4.]
 [ -7.]
 [ 13.]
 [-13.]]
[07-18 11:33:32][INFO] Sustitución hacia atrás
[07-18 11:33:32][INFO] i = 2
[07-18 11:33:32][INFO] suma = [13.]
[07-18 11:33:32][INFO] U[i, i] = 3.0
[07-18 11:33:32][INFO] y[i] = [13.]
[07-18 11:33:32][INFO] i = 1
[07-18 11:33:32][INFO] suma = [-5.]
[07-18 11:33:32][INFO] U[i, i] = -1.0
[07-18 11:33:32][INFO] y[i] = [-7.]
[07-18 11:33:32][INFO] i = 0
[07-18 11:33:32][INFO] suma = [5.]
[07-18 11:33:32][INFO] U[i, i] = 1.0
[07-18 11:33:32][INFO] y[i] = [4.]


array([[-1.],
       [ 2.],
       [ 0.],
       [ 1.]])