# Descomposición LU

In [1]:
%load_ext autoreload

In [2]:
%autoreload 2
from src import descomposicion_LU, eliminacion_gaussiana

A = [[1, 1, 0, 3], [2, 1, -1, 1], [3, -1, -1, 2], [-1, 2, 3, -1]]
b = [4,1,-3,4]
L, U = descomposicion_LU(A)

[07-16 17:47:08][INFO] 2024-07-16 17:47:08.612134
[07-16 17:47:08][INFO] 
[[ 1.  1.  0.  3.]
 [ 0. -1. -1. -5.]
 [ 0. -4. -1. -7.]
 [ 0.  3.  3.  2.]]
[07-16 17:47:08][INFO] 
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]
[07-16 17:47:08][INFO] 
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]
[07-16 17:47:08][INFO] 
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]


In [3]:
# Verificación
import numpy as np

np.matmul(L, U)

array([[ 1.,  1.,  0.,  3.],
       [ 2.,  1., -1.,  1.],
       [ 3., -1., -1.,  2.],
       [-1.,  2.,  3., -1.]])

In [4]:
# Solución, matriz aumentada
Ab = [[1, 1, 0, 3, 4], [2, 1, -1, 1, 1], [3, -1, -1, 2, -3], [-1, 2, 3, -1, 4]]
eliminacion_gaussiana(Ab)

[07-16 17:47:08][INFO] 
[[  1   1   0   3   4]
 [  0  -1  -1  -5  -7]
 [  0  -4  -1  -7 -15]
 [  0   3   3   2   8]]
[07-16 17:47:08][INFO] 
[[  1   1   0   3   4]
 [  0  -1  -1  -5  -7]
 [  0   0   3  13  13]
 [  0   0   0 -13 -13]]
[07-16 17:47:08][INFO] 
[[  1   1   0   3   4]
 [  0  -1  -1  -5  -7]
 [  0   0   3  13  13]
 [  0   0   0 -13 -13]]


array([-1.,  2.,  0.,  1.])

In [23]:
%autoreload 2
from src import eliminacion_gaussiana, descomposicion_LU
A = [[1, 2,-1, -1], [2, 3, -2,  -3], [1, 1, 1, 0], [1, 4, -1, 3]]

L, U = descomposicion_LU(A)
print(L)
print(U)

[07-16 17:51:46][INFO] 
[[ 1.  2. -1. -1.]
 [ 0. -1.  0. -1.]
 [ 0. -1.  2.  1.]
 [ 0.  2.  0.  4.]]
[07-16 17:51:46][INFO] 
[[ 1.  2. -1. -1.]
 [ 0. -1.  0. -1.]
 [ 0.  0.  2.  2.]
 [ 0.  0.  0.  2.]]
[07-16 17:51:46][INFO] 
[[ 1.  2. -1. -1.]
 [ 0. -1.  0. -1.]
 [ 0.  0.  2.  2.]
 [ 0.  0.  0.  2.]]
[07-16 17:51:46][INFO] 
[[ 1.  2. -1. -1.]
 [ 0. -1.  0. -1.]
 [ 0.  0.  2.  2.]
 [ 0.  0.  0.  2.]]
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 1.  1.  1.  0.]
 [ 1. -2.  0.  1.]]
[[ 1.  2. -1. -1.]
 [ 0. -1.  0. -1.]
 [ 0.  0.  2.  2.]
 [ 0.  0.  0.  2.]]


In [24]:
np.matmul(L, U)

array([[ 1.,  2., -1., -1.],
       [ 2.,  3., -2., -3.],
       [ 1.,  1.,  1.,  0.],
       [ 1.,  4., -1.,  3.]])

In [33]:
%autoreload 2
from src import eliminacion_gaussiana, descomposicion_LU, resolver_LU
b = [4,1,-3,4]
resolver_LU(L, U, b)

[07-16 17:53:55][INFO] Completar!
